### ISSUE TITLE
Fatal error - unexpected end of file formdisplay.php

### ISSUE THREAD

**Issue by skenow** [jegelstaff/formulize#305]
Installing from the master branch (as standalone, and as a module in ImpressCMS 1.3.x) - after installation finishes, going to the module administration page for Formulize results in a blank page. PHP error log indicates an unexpected EOF for formdisplay.php.

**Comment by jegelstaff** [comment]
Thanks Steve! Sorry for the delay, and thank you for tracking this down.

After looking at the place where the issue was, I think the right place to add the brace is a little higher. I have done this in the latest commit: https://github.com/jegelstaff/formulize/commit/15c2f45f6f263be49bf282a075c34c59c30677db

If you put it where you have it in your branch, then the "special validation logic" feature is captured inside the "if we're not on mobile" condition, and it should be independent of that. The test for mobile is only to support the instantiation, or not, of the necessary javascript for date selectors when you're not on mobile.

--Julian

**Comment by skenow** [comment]
Thanks, Julian!
