### ISSUE TITLE
Fatal error when saving "Menu Entries" tab in PHP 8.1.6

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#336]
From error log:
> PHP Fatal error:  Uncaught Error: Undefined constant "all" in /modules/formulize/admin/save/application_menu_entries_save.php:67
> Stack trace:
>  #.0 /modules/formulize/admin/save.php(98): include()
>  #.1 {main}
>   thrown in /modules/formulize/admin/save/application_menu_entries_save.php on line 67

The line in question is `$Links = $application_handler->getMenuLinksForApp($appid, all);`

**Comment by jegelstaff** [comment]
Interesting. There should be quotes around all: $appid, 'all'

PHP 8 decides to fatal error on undefined constants. Very annoying. They really put beautiful code way ahead of making maintenance easy. I can sort of understand... but there's a balance to be struck and I think it's way too far in one direction. When programmers make ivory tower decisions that break things that were working just fine, I lose a lot of patience.

Anyway, because this was not correct before, correcting it now might alter the behaviour of the application (which is the exact kind of reason why PHP 8 forces you to not make mistakes like this anymore).  The code in question is part of saving the order of the menu links, and if it starts retrieving more or less links than it used to, it will give a very clear message about this (a few lines lower down).

**Comment by tikyon** [comment]
I add the quotes to 'all' and the fatal error went away.

**Comment by jegelstaff** [comment]
Fixed in d368a160c3124c62a7479501cc505a6d5cb124e0
