### ISSUE TITLE
{BLANK} filter not working with simple Yes/No radio button

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#341]
When I use {BLANK} filter for this element type on list screen, it results in "Error: could not count master results." due to the a typo in the SQL query. There is an extra " 1" that appears after IS NULL statement in `$mainFormWhereClause` part.

> WHERE main.entry_id>0 AND ( ( main.element_handle ='1' or main.element_handle IS NULL **1** ) )

**Comment by jegelstaff** [comment]
Ack! Good catch! I'll check that out, should be very simple.

**Comment by jegelstaff** [comment]
This is fixed with commit 56ed356d5

The problem was more PHP 8 silliness. In PHP 7 and earlier:

$haystack = "something";
$needle = ""; // empty string
strstr($haystack, $needle); // equals false, because the needle is not in the haystack

In PHP 8, empty strings for the needle always result in true, for strstr and strpos and various other string functions.

This is in my opinion total insanity. But they never asked me, and I did not involve myself in the PHP 8 development effort. I have said my piece about this and we must move on. https://github.com/php/php-src/issues/8582#issuecomment-1359054194

It won't change in a future version of PHP, nor should it because we don't want another logic inversion!!

Anyway, with this tiny fix, the following search terms now work as expected:

For a "yes": Yes, YES, yES, Y, y, S, es, and so on (the word Yes or any substring of the word, and also this works for Oui for a French user, etc)

For a "no": No, NO, nO, N, n, O, o, etc...

And {BLANK} and !{BLANK} work too, just like before.

--Julian
