### ISSUE TITLE
Feedback for template screen

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#345]
Hi Julian,

We found that once the table becomes large (300+ entries), the page load time on the template screen also got longer. I was able to pinpoint the cause to be due to the page trying to grab all entries in the table when we weren't utilizing the `entry_id` (i.e. the value is empty). 

My quick fix was to add a check `if (!empty($entry_id)) {}` around lines 198-204 in file modules/formulize/class/templateScreen.php. This works for my usage, since I would do a separate `getData()` in the code.php file anyway.

**Comment by jegelstaff** [comment]
Very clever catch. Yes, the template screen is meant to display an entry (though you could use it for a list... but more sensible to use a list screen for that probably). And you might have other uses for it in other situation.

So anyway, when there is no specific entry, it makes sense to not gather data to prepopulate the variables, and instead leave that up to the developer to do however they see fit in the code. If there is an entry then 198-204 are meant to simplify things and just give you what you need for making the template you want.

If you make a pull request for this I'll merge it in.

**Comment by jegelstaff** [comment]
Interesting. I see a comment in the code that gathering the data could be an option in the Templates tab for the Templates Screens. I think the idea of putting the IF condition around it is a simpler solution that addresses most cases. But perhaps there are a variety of data gathering scenarios that could be addressed and might benefit from being made available as options. ie: load the entry, load all entries, load a related entry from a relationship? 

I think any series of entries that you might want probably means you should make a list screen that isolates the entries you want, because that's what list screens are for. But there are conceivably some dashboard situations or other things where maybe you would use a template screen instead and getting something other than a single entry of data would make sense? And that could/should be a configuration option?

**Comment by tikyon** [comment]
I agree that having options to toggle the behaviour would be good in the long term.
